### ISSUE TITLE
Plotting of runtime data from Gazebo

### ISSUE THREAD

**Issue by michoy** [vortexntnu/uuv-simulator#13]
It would be very beneficial to easily plot runtime data from Gazebo. 

Examples of use cases:
- Plotting of path-following performance. Desired trajectory vs actual trajectory
- Plotting of commanded thruster inputs

**Comment by theBadMusician** [comment]
Explore data logging solutions using ROS bags, as well as other tools. Look into writing a Python based data visualization program to plot various topics.

Best current solution for real-time simulator data monitoring is using Gazebo with Webviz interface.

**Comment by ingar-eh** [comment]
Ros has a built in program called Rviz, ran using $rosrun rviz rviz. Out of the current topics in the simulator the only one I managed to plot was manta/pose_gt which shows the trajectory of Manta. When trying to plot other topics they either didn't show up, or displayed an error and procedeed to not show up. But if I could get the other topics to work as well it could be very useful.

**Comment by chrstrom** [comment]
The repo https://github.com/vortexntnu/run_analysis can be used to visualize Odometry og Desired Thrust data graphically.

**Comment by michoy** [comment]
I have done some work on 

- Converting from bag to csv
- Interpolating measurements form different nodes
- Plotting of data with seaborn / pyplot

The interpolated csv files can be used for visualization with many tools.

**Comment by michoy** [comment]
A note about webviz for live visualization should be added
