### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by michoy** [vortexntnu/uuv-simulator#15]
Learn about the simulator and write documentation about it in source code and readme. Follow guidelines on documentation from wiki.

**Comment by michoy** [comment]
Tasks: 

- [ ] Add readmes to top level folders
- [ ] Refactor top level readme

**Comment by chrstrom** [comment]
This was sort of? done, but closing since the uuv_simulator wiki is very extensive, and we are moving away from the "vortex custom uuv simulator" baked-in sim..
