### ISSUE TITLE
Create model (visual and physical) for new AUV

### ISSUE THREAD

**Issue by chrstrom** [vortexntnu/uuv-simulator#18]
The new AUV will have dynamics and configurations that need to be captured in a parameter list. The simulator needs these to accurately represent the real-world AUV.

**Comment by ingar-eh** [comment]
Current list of what we need from hardware:

-CAD-model
-Dimensions
-Mass
-Density
-Volume of displacement
-Center of gravity
-Center of buoyancy
-Damping coefficients?(some code referenced damping coefficients, not sure if it's relevant)

This list is not final as there might be some parameters I have missed, feel free to add.
