### ISSUE TITLE
Import acoustics to the simulator 

### ISSUE THREAD

**Issue by oyssolbo** [vortexntnu/uuv-simulator#22]
Need to import the acoustics into the simulator, such that the algorithms can be tested without the AUV

**Comment by theBadMusician** [comment]
Explore data logging solutions using ROS bags, look into other tools as well. Would be nice to write a custom Python based data visualization program to plot various topics.

Best current solution for real-time simulator logging is using Gazebo with Webviz interface.

**Comment by michoy** [comment]
There is no standard way of adding this, thus it will probably be very time-consuming to implement. We therefore close the issue for now
