### ISSUE TITLE
Build simulator on Melodic and Gazebo 9

### ISSUE THREAD

**Issue by michoy** [vortexntnu/uuv-simulator#4]
The simulator does not build on melodic instead of kinetic. The package that does not buil is uuv_sensor_ros_plugins.

---

Error log: 

Errors     << uuv_sensor_ros_plugins:make /home/michael/manta_ws/logs/uuv_sensor_ros_plugins/build.make.004.log
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/uuv_gazebo_ros_camera_plugin.dir/src/UnderwaterCameraROSPlugin.cc.o] Error 4
make[1]: *** [CMakeFiles/uuv_gazebo_ros_camera_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/uuv_gazebo_ros_rpt_plugin.dir/src/RPTROSPlugin.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/uuv_gazebo_ros_dvl_plugin.dir/src/DVLROSPlugin.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [CMakeFiles/uuv_gazebo_ros_rpt_plugin.dir/src/ROSBasePlugin.cc.o] Error 4
make[1]: *** [CMakeFiles/uuv_gazebo_ros_dvl_plugin.dir/all] Error 2
make[1]: *** [CMakeFiles/uuv_gazebo_ros_rpt_plugin.dir/all] Error 2
make: *** [all] Error 2
cd /home/michael/manta_ws/build/uuv_sensor_ros_plugins; catkin build --get-env uuv_sensor_ros_plugins | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << uuv_sensor_ros_plugins:make                [ Exited with code 2 ]
Failed    <<< uuv_sensor_ros_plugins                     [ 55.6 seconds ]      
Abandoned <<< manta_description                          [ Unrelated job failed ]
Abandoned <<< uuv_descriptions                           [ Unrelated job failed ]

**Comment by michoy** [comment]
Replacing our uuv folders with those from uuv_simulator did not affect the problem. This makes me think the problem is rooted in the installation or setup

**Comment by michoy** [comment]
The file /uuv_sensor_plugins/uuv_sensor_ros_plugins looks very interessting

**Comment by chrstrom** [comment]
> There might be a case of "but it's working on _my_ computer" here... I am not able to reproduce the build error you are getting. I've attached my successful build log below. Definitely need to look into ways of reproducing the error.
[build.make.000.log](https://github.com/vortexntnu/manta-auv-simulator/files/5215006/build.make.000.log)

**Comment by michoy** [comment]
That is very interesting! The bug is probably caused by the installation or the dependencies then. What path variables did you use?

**Comment by michoy** [comment]
Path variables do not affect the problem

**Comment by michoy** [comment]
Full log of failed build: 
[build.make.009.log](https://github.com/vortexntnu/manta-auv-simulator/files/5220125/build.make.009.log)

**Comment by ingar-eh** [comment]
The simulator is up and running on my computer. I mostly followed the readme in manta-auv.

**Comment by heiring** [comment]
> The simulator is up and running on my computer. I mostly followed the readme in manta-auv.

works for me too

**Comment by chrstrom** [comment]
> > The simulator is up and running on my computer. I mostly followed the readme in manta-auv.
> 
> works for me too

It seems like the simulator works on melodic if you have not previously installed kinetic?

**Comment by michoy** [comment]
> It seems like the simulator works on melodic if you have not previously installed kinetic?

It definitely seems to be working on clean installs. I'll try it out on my computer today, and if it works we can close the issue

**Comment by oyssolbo** [comment]
Had some issues using 
git clone "URL for vortex_msgs". 


The simulator managed to  build when I used 
git clone -b melodic "URL for vortex_msgs"

**Comment by chrstrom** [comment]
> Had some issues using
> git clone "URL for vortex_msgs".
> 
> The simulator managed to build when I used
> git clone -b melodic "URL for vortex_msgs"

Known issue, README needs to be updated, or better yet, merge the melodic branch into master.

**Comment by michoy** [comment]
Update: removing and reinstalling all of ros melodic and the workspace did not solve the issue for me. 

Clean ubuntu install is up next..

**Comment by wych1005** [comment]
> Had some issues using
> git clone "URL for vortex_msgs".
> 
> The simulator managed to build when I used
> git clone -b melodic "URL for vortex_msgs"

The simulator is up and running on my PC as well, after I git cloned the Melodic branch of vortex_msgs

**Comment by oyssolbo** [comment]
Since the simulator works for nearly everyone - poor Michael - this issue is hereby closed.
