### ISSUE TITLE
Remove/clarify dependencies on outside repositories

### ISSUE THREAD

**Issue by michoy** [vortexntnu/uuv-simulator#6]
The simulator depends on the packages _vortex_ and _navigation_launch_ from manta-auv. This is a problem, since dependencies accross repos reduce the maintainability of our system.

**Comment by chrstrom** [comment]
Will making the simulator standalone introduce another layer of complexity in terms of keeping them both up to date? As in, how will we manage syncronizing changes in the main repo and the simulator repo?

**Comment by michoy** [comment]
Fair point. We would have to add the parameters for Mantas in both repos, and remember to update both when updating the model. I would say it boils down to what we prioritize: having a standalone simulator or reducing the chance of error when updating the model. We should keep in mind that the model won't be updated often

**Comment by chrstrom** [comment]
I compiled a list of what needs to be copied from manta-auv into manta-auv-simulator for the simulator and mission to launch in it's current state:
```
    localization from manta-auv
    vortex-msgs from vortex-msgs
        -> roslaunch simulator_launch cybernetics_pool.launch works here
    vortex from manta-auv/control
    thruster-interface from manta-auv/control
    vortex-allocator from manta-auv/control
    dp_controller from manta-auv/control
    interface from manta-auv/control
    autopilot from manta-auv/control
    los_guidance from manta-auv/guidance
    reference_model from manta-auv/guidance
        -> roslaunch vortex manta_simulator.launch works here
    finite_state_machine from manta-auv/mission
        -> roslaunch finite_state_machine pooltest.launch works here                                                                
```

~It seems to me like keeping the dependency on manta-auv is OK for the simulator, **as long as** the README's are rewritten to 1. give enough information to set up the simulator successfully, and 2. points this dependency out clearly.~

Simulator should still build and run with the model, without needing the Vortex-AUV repo.

**Comment by chrstrom** [comment]
Title was changed to reflect how running the simulator can depend on outside repositories, but these dependencies must be clearly pointed out.

**Comment by chrstrom** [comment]
It would also be nice to add a note that we always guarantee that the development branches on Vortex-AUV and Vortex-Simulator will work together. This will hopefully reduce the amount of confusion/errors with using the simulator when working on the repos separately.
