### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by chrstrom** [vortexntnu/uuv-simulator#7]
The README for this repo needs to be updated for the switch to melodic, as well as be synced with the simulator section in https://github.com/vortexntnu/manta-auv/blob/master/README.md

**Comment by chrstrom** [comment]
The README in the simulator repo does a worse job at explaining how to start missions etc. than the [main repo](https://github.com/vortexntnu/Vortex-AUV). Consider copying step 6 from there, and maybe adding more information.

**Comment by stefalarse** [comment]
dependency on Vortex-AUV repo should be clarified
